sudo: required

branches:
  only:
    - master

services:
  - docker

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache

before_install:
  - export VERSION=$(sed -n 's/^version := "\(.*\)"$/\1/gp' build.sbt)
  - docker build --build-arg VERSION=$VERSION -t taylord/kafka-manager .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push -t $VERSION taylord/kafka-manager
