sudo: required

services:
  - docker

before_install:
 - docker build --build-arg VERSION=$(sed -n 's/^version := "\(.*\)"$/\1/gp' build.sbt) -t taylord/kafka-manager .
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push -t $(sed -n 's/^version := "\(.*\)"$/\1/gp' build.sbt) taylord/kafka-manager
